# =============================================================================
# Script: 10_annotation_diagnostics_and_confidence_assessment.R
# Description: Assesses confidence of SingleR annotations using pruned labels
#              and delta score distributions. Cross-checks annotated cell
#              types against canonical marker expression to validate that
#              assigned labels match underlying biology.
# Input:  'seurat_obj_filtered' and 'multi_res' from script 09
#          data/metadata/canonical_marker.csv
#            (Note: This file is manually curated from literature/established
#             cell biology knowledge — NOT auto-generated by SingleR/Seurat.
#             It lists canonical marker genes for each major cell type used
#             to validate SingleR annotations.)
# Output: 'seurat_obj_filtered' with SingleR_pruned_label column added
#         results/marker_support_by_celltype.csv
#         results/marker_support_by_celltype_flagged.csv
#         Delta distribution plot, pruned label UMAP
# =============================================================================


library(Seurat)
library(SingleR)
library(dplyr)
library(Matrix)
library(ggplot2)

# --- Section 1: Pruned labels (conservative annotation) ---

# SingleR sets ambiguous cell assignments to NA in pruned.labels
# High proportion of non-NA indicates confident annotation overall
seurat_obj_filtered$SingleR_pruned_label <- multi_res$pruned.labels

cat("Pruned label distribution (NA = ambiguous):\n")
print(table(seurat_obj_filtered$SingleR_pruned_label, useNA = "ifany"))

# Visualize ambiguous cells on UMAP (grey = ambiguous)

p_pruned <- DimPlot(seurat_obj_filtered, group.by = "SingleR_pruned_label", 
                    label = TRUE, repel = TRUE, na.value = "grey",
                    label.size = 3) +
  ggtitle("SingleR Pruned Labels (Ambiguous = Grey)") +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"))

ggsave("figures/umap_pruned_labels.png", plot = p_pruned, width = 10, height = 8, dpi = 300, bg = "white")


# --- Section 2: Delta score distribution ---

# Delta = difference between top and second-best score for each cell
# Higher delta = more confident assignment
plotDeltaDistribution(multi_res)

# --- Section 3: Marker-based validation ---

# Load canonical marker list for each cell type
marker_table <- read.csv("data/metadata/canonical_marker.csv", stringsAsFactors = FALSE)

# Keep only cell types present in both marker table and Seurat object
cell_types <- intersect(
  unique(marker_table$CellType),
  unique(seurat_obj_filtered$cell_type_cleaned)
)

# Keep only markers present in the dataset
all_markers <- unique(marker_table$canonicalMarker)
all_markers <- all_markers[all_markers %in% rownames(seurat_obj_filtered)]

# Calculate fraction of cells expressing each marker and average expression,
# per annotated cell type
results <- lapply(cell_types, function(ct) {
  cells <- WhichCells(seurat_obj_filtered, expression = cell_type_cleaned == ct)
  if (length(cells) == 0) return(NULL)
  
  expr <- GetAssayData(seurat_obj_filtered, slot = "data")[all_markers, cells, drop = FALSE]
  fraction <- rowMeans(expr > 0)
  avg_expr <- rowMeans(expr)
  
  data.frame(
    cellType = ct,
    marker = all_markers,
    fraction_expressing = fraction,
    avg_expression = avg_expr
  )
})

marker_support_table <- do.call(rbind, results)

write.csv(marker_support_table, "results/marker_support_by_celltype.csv", row.names = FALSE)
cat("Saved: results/marker_support_by_celltype.csv\n")


# --- Optional diagnostic checks ---

# How many canonical markers are present in the dataset?
cat("Canonical markers found in dataset:", 
    sum(marker_table$canonicalMarker %in% rownames(seurat_obj_filtered)), 
    "out of", nrow(marker_table), "\n")

# Summary statistics of marker support across all cell types
cat("\nSummary of fraction expressing:\n")
print(summary(marker_support_table$fraction_expressing))

cat("\nSummary of average expression:\n")
print(summary(marker_support_table$avg_expression))

# Example: inspect marker support for a specific cell type
cat("\nMarker support for T cells:\n")
print(subset(marker_support_table, cellType == "T cells"))


# --- Section 4: Flag strong vs weak marker support ---

# A marker is "Strong" support for a cell type if it is expressed in a
# meaningful fraction of cells AND at meaningful average expression
fraction_threshold <- 0.3
expression_threshold <- 0.7

marker_support_table$strong_marker <- with(marker_support_table,
                                           fraction_expressing > fraction_threshold & avg_expression > expression_threshold
)
marker_support_table$marker_flag <- ifelse(marker_support_table$strong_marker, "Strong", "Weak")

write.csv(marker_support_table, "results/marker_support_by_celltype_flagged.csv", row.names = FALSE)
cat("Saved: results/marker_support_by_celltype_flagged.csv\n")

cat("\nStrong vs Weak markers per cell type:\n")
print(table(marker_support_table$cellType, marker_support_table$marker_flag))
